# Generated by Django 4.1.7 on 2023-03-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('other_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('updating', 'updating'), ('deleted', 'deleted'), ('ended', 'ended')], default='updating', max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('sumary', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='comic/')),
                ('gender', models.CharField(choices=[('male', 'male'), ('demale', 'female'), ('unisex', 'unisex')], default='unisex', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('chap', models.IntegerField(default=0)),
                ('genres', models.ManyToManyField(related_name='comics', to='comic.genre')),
            ],
        ),
    ]
