# Generated by Django 4.1.7 on 2023-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_alter_comic_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='other_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
