# Generated by Django 4.1.7 on 2023-03-22 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_comic_view_day_comic_view_month_comic_view_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_num', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='comic.comic')),
            ],
        ),
    ]
