# Generated by Django 4.1.7 on 2023-03-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0007_alter_comic_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='author',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
