# Generated by Django 4.1.7 on 2023-03-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0009_alter_chap_name_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chap',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='chap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.chap'),
        ),
    ]
