# Generated by Django 4.1.7 on 2023-03-23 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comic', '0010_alter_chap_name_alter_comment_chap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='UserComment',
        ),
    ]
