# Generated by Django 4.1.7 on 2023-03-23 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0013_alter_comment_chap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comic', to='comic.comic'),
            preserve_default=False,
        ),
    ]
