# Generated by Django 4.1.7 on 2023-03-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0018_alter_comment_chap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.chap'),
        ),
    ]
