# Generated by Django 4.1.7 on 2023-03-24 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0021_alter_rating_comic_alter_rating_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_folder', models.CharField(max_length=100)),
                ('chap', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='comic.chap')),
            ],
        ),
    ]
