# Generated by Django 4.1.7 on 2023-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0022_chapimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapimage',
            name='image_folder',
        ),
        migrations.AddField(
            model_name='chapimage',
            name='images',
            field=models.FileField(default=1, upload_to='comic_img/'),
            preserve_default=False,
        ),
    ]
