# Generated by Django 4.1.7 on 2023-03-24 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0023_remove_chapimage_image_folder_chapimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='chap',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='comic_img/'), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='ChapImage',
        ),
    ]
