# Generated by Django 4.1.7 on 2023-03-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
