# Generated by Django 4.1.7 on 2023-03-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_options_alter_myuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', upload_to='avatar/'),
        ),
    ]
